### PR TITLE
Updated Contributors Guide and Introduced License Check Workflow

### PR DESCRIPTION
**Pull request by longtr28**
- Expanded CONTRIBUTING.md with detailed instructions for contributions
- Added workflow and license-check.yml file to automate license checks
- Added liccheck dependency to requirements.txt
- Added name to README.md as per contributor guidelines

### CODE REVIEW

**Comment by decryptofy** [comment]
This looks like a nice contribution, thank you! Can you please add liccheck as dependency also to the pyproject.toml to keep it in sync with the requirements.txt? This might be another good addition to the CONTRIBUTING.md, too. Currently, it appears that both (.toml,.txt) are needed to satisfy all possible scenarios and external tools.

**Comment by decryptofy** [comment]
It appears we also need to add these licenses to the license-check.yml.
Mozilla Public License 2.0 (MPL 2.0)
Apache License, Version 2.0
Historical Permission Notice and Disclaimer (HPND)
Otherwise, it appears the GitHub check does not recognize this properly

**Comment by longtr28** [comment]
Thank you for your feedback! I've updated pyproject.toml, updated the authorized licenses, and added a comment in CONTRIBUTING.md to track dependencies in pyproject.toml and requirements.txt. Please let me know if I can address anything else.

**Comment by decryptofy** [comment]
so, either liccheck behaves differently when executed locally, or indeed, we need to put the verbatim license text into license-check.yml. Apache worked, but the other two did not. Please try with:
Mozilla Public License 2.0 (MPL 2.0)
Historical Permission Notice and Disclaimer (HPND)
This should work and then I can accept this (would be nice to keep the GitHub workflow such that it works)

**Comment by decryptofy** [comment]
Awesome :+1:  -- merged

**Pull request merged**
